# -*- coding: utf-8 -*-
"""asigment 1 del 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xqqhD6WMFKbhWGrnwNFZdtQYbhfh3J_
"""

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms

# Ladda ner MNIST
train_data = torchvision.datasets.MNIST(
    root='./data',
    train=True,
    transform=transforms.ToTensor(),
    download=True
)

test_data = torchvision.datasets.MNIST(
    root='./data',
    train=False,
    transform=transforms.ToTensor()
)

train_loader = torch.utils.data.DataLoader(train_data, batch_size=64)
test_loader = torch.utils.data.DataLoader(test_data, batch_size=64)

class Perceptron(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        x = x.view(-1, 784)
        return self.layers(x)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Använder: {device}")

model = Perceptron().to(device)
optimizer = torch.optim.Adam(model.parameters())
criterion = nn.CrossEntropyLoss()

for epoch in range(5):
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1} klar!")

print("Träning klar!")