# -*- coding: utf-8 -*-
"""Assignment 1 del 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9_oYLFCGhqzUKzu79EjFLR-yE2Sxtv5

Dogs vs Cats
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
os.makedirs('/content/drive/MyDrive/AI 1/assignment3/modeller', exist_ok=True)
print("Drive kopplad och mappar skapade!")

import os
import json

os.makedirs('/root/.kaggle', exist_ok=True)

# Skapa kaggle.json med rätt format
creds = {
    "username": "alexiakazim",
    "key": "KGAT_379a63ed559ee7e0e88cc6ecee6ec1a1"
}

with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump(creds, f)

os.chmod('/root/.kaggle/kaggle.json', 0o600)
print("Kaggle API klar!")

import kagglehub
import os

# Ladda ner datasetet
path = kagglehub.dataset_download("blourdhuraju/dogs-vs-cats-classification")
print("Path to dataset files:", path)

# Kolla vad som finns i mappen
for item in os.listdir(path):
    print(item)

import os

inner_path = '/kaggle/input/dogs-vs-cats-classification/dogs-vs-cats-classification'

# Kolla antal bilder
for folder in ['train', 'test', 'validation']:
    for animal in ['dogs', 'cats']:
        path = os.path.join(inner_path, folder, ani mal)
        antal = len(os.listdir(path))
        print(f"{folder}/{animal}: {antal} bilder")

"""1. Importera bibliotek och förbereda datan. Ladda in hundarna och katterna för att förbereda dem för tärning med data augmentation."""

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import os

# Sökväg till datan
data_path = '/kaggle/input/dogs-vs-cats-classification/dogs-vs-cats-classification'

# Förbereda bilderna för träning (med augmentation)
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),      # ändra storlek till 224x224
    transforms.RandomHorizontalFlip(),  # spegelvänd slumpmässigt
    transforms.RandomRotation(10),      # rotera lite
    transforms.ToTensor(),              # omvandla till tal
    transforms.Normalize(               # normalisera
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
])

# Förbereda testbilder (ingen augmentation!)
test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
])

# Ladda in datan
train_data = torchvision.datasets.ImageFolder(
    os.path.join(data_path, 'train'),
    transform=train_transform)

test_data = torchvision.datasets.ImageFolder(
    os.path.join(data_path, 'test'),
    transform=test_transform)

val_data = torchvision.datasets.ImageFolder(
    os.path.join(data_path, 'validation'),
    transform=test_transform)

# Skapa data loaders
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32)
val_loader = DataLoader(val_data, batch_size=32)

print(f"Träningsbilder:     {len(train_data)}")
print(f"Testbilder:         {len(test_data)}")
print(f"Valideringsbilder:  {len(val_data)}")

"""2. Bygg ett eget CNN för hund vs katt.
Vi bygger ett från grunden som vi gjorde med MNIST.
"""

import torch
import torch.nn as nn

class CNN_HundKatt(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_layers = nn.Sequential(
            # Första lagret
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Dropout(0.25),

            # Andra lagret
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Dropout(0.25),

            # Tredje lagret
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Dropout(0.25)
        )

        self.fc_layers = nn.Sequential(
            nn.Linear(128 * 28 * 28, 512),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(512, 2)  # 2 klasser: hund eller katt
        )

    def forward(self, x):
        x = self.conv_layers(x)
        x = x.view(x.size(0), -1)
        return self.fc_layers(x)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Använder: {device}")

model = CNN_HundKatt().to(device)
print("CNN modell skapad!")

"""3. Träna CNN på hund vs katt
Tränar nätverket och mäter noggranheten efter varje epoch.   
"""

import time
import os

os.makedirs('/content/AI 1/assignment3/modeller', exist_ok=True)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

total_start = time.time()

for epoch in range(10):
    epoch_start = time.time()

    # Träning
    model.train()
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()

    # Mät noggrannhet på valideringsdata
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images = images.to(device)
            labels = labels.to(device)
            output = model(images)
            _, predicted = torch.max(output, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    noggrannhet = 100 * correct / total
    epoch_tid = time.time() - epoch_start
    print(f"Epoch {epoch+1} → Noggrannhet: {noggrannhet:.2f}% | Tid: {epoch_tid:.1f}s")

    # Spara modellen
    torch.save(model.state_dict(),
        f'/content/drive/MyDrive/AI 1/assignment3/modeller/hundkatt_epoch_{epoch+1}.pth')

total_tid = time.time() - total_start
print(f"\nTräning klar! Total tid: {total_tid:.1f}s")

"""4. Transfer learning med ResNet50
Vi använder ResNet50 som är redan tränas på miljoner bilder, vi anpassar bara sista lagret till vår träningsdata.
"""

from torchvision.models import resnet50, ResNet50_Weights

# Ladda in det färdiga ResNet50 nätverket
model_resnet = resnet50(weights=ResNet50_Weights.IMAGENET1K_V1)

# Frys alla lager - vi vill inte ändra dem!
for param in model_resnet.parameters():
    param.requires_grad = False

# Byt ut sista lagret till vårt eget (hund vs katt)
model_resnet.fc = nn.Sequential(
    nn.Linear(2048, 512),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(512, 2)  # 2 klasser: hund eller katt
)

model_resnet = model_resnet.to(device)
print("ResNet50 modell klar!")

"""Träna på ResNet på hund vs katt, vi tränar bara på sista lagret."""

import time
import os

optimizer_resnet = torch.optim.Adam(
    model_resnet.fc.parameters(),  # träna bara sista lagret!
    lr=0.001
)
criterion = nn.CrossEntropyLoss()

total_start = time.time()

for epoch in range(10):
    epoch_start = time.time()

    # Träning
    model_resnet.train()
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        optimizer_resnet.zero_grad()
        output = model_resnet(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer_resnet.step()

    # Mät noggrannhet
    model_resnet.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images = images.to(device)
            labels = labels.to(device)
            output = model_resnet(images)
            _, predicted = torch.max(output, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    noggrannhet = 100 * correct / total
    epoch_tid = time.time() - epoch_start
    print(f"Epoch {epoch+1} → Noggrannhet: {noggrannhet:.2f}% | Tid: {epoch_tid:.1f}s")

    # Spara modellen
    torch.save(model_resnet.state_dict(),
        f'/content/drive/MyDrive/AI 1/assignment3/modeller/resnet_epoch_{epoch+1}.pth')

total_tid = time.time() - total_start
print(f"\nTräning klar! Total tid: {total_tid:.1f}s")